export let contacto = 
[{
    title:    'Correo Electronico',
    type:     'contacto',
    icon:     '',            
    subtitle: 'Correo',
    mirar:    'mailto:sanchesedgar97@gmail.com',
    source:   '',
    img:      'https://qrcode.tec-it.com/API/QRCode?data=mailto%3asanchesedgar97%40gmail.com%3fsubject%3dContacto%26body%3dHola+soy...&color=%23ffffff&backcolor=%23ffffff&istransparent=True',
    paragraph:'',
    tags:     '',
},{
    title:    'Facebook',
    type:     'contacto',
    icon:     '',            
    subtitle: 'Perfil de Facebook',
    mirar:    'https://www.facebook.com/edgarulises.sanchezizquierdo',
    source:   '',
    img:      'https://qrcode.tec-it.com/API/QRCode?data=https%3a%2f%2fwww.facebook.com%2fedgarulises.sanchezizquierdo&color=%23ffffff&backcolor=%23ffffff&istransparent=True',
    paragraph:'',
    tags:     '',
},{
    title:    'LinkedIn',
    type:     'contacto',
    icon:     '',            
    subtitle: 'Perfil de LinkedIn',
    mirar:    'https://www.linkedin.com/in/Trongar',
    source:   '',
    img:      'https://qrcode.tec-it.com/API/QRCode?data=https%3a%2f%2fwww.linkedin.com%2fin%2fTrongar&color=%23ffffff&backcolor=%23ffffff&istransparent=True',
    paragraph:'',
    tags:     '',
},{
    title:    'Numero de Telefono',
    type:     'contacto',
    icon:     '',            
    subtitle: 'Agregar contacto',
    mirar:    'tel:+529141089348',
    source:   '',
    img:      'https://qrcode.tec-it.com/API/QRCode?data=tel%3a%2b529141089348&color=%23ffffff&backcolor=%23ffffff&istransparent=True',
    paragraph:'',
    tags:     '',
},
];